language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"


before_deploy:
  - zip -r spring-blog-web.zip *
  - mkdir -p deploy
  - mv spring-blog-web.zip deploy/spring-blog-web.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: socurites-travis-ci-build
  region: ap-northeast-1
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

notifications:
  email:
    recipients:
      - socurites@gmail.com