language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

env:
  - deploy-dir=before-deploy
  - deipoy-zip=spring-blog-web.zip

before_deploy:
#  - zip -r spring-blog-web.zip *
#  - mkdir -p deploy
#  - mv spring-blog-web.zip deploy/spring-blog-web.zip
  - mkdir -p $deploy-dir
  - cp script/*.sh $deploy-dir
  - cp appspec.yml $deploy-dir
  - cp build/libs/*.jar deploy-dir
  - zip -r $deploy-zip $before-deploy/*

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: socurites-travis-ci-build
    region: ap-northeast-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: socurites-travis-ci-build
    key: $delpoy-zip
    bundle_type: zip
    application: spring-blog-web
    deployment_group: spring-blog-web-group
    region: ap-northeast-1
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - socurites@gmail.com