spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '790215119095-f2i7eik4t79ap6ts2hcb0mkk913bd4tf.apps.googleusercontent.com'
            client-secret: '2GRfbG5cs3oRwbhL_D0YqYka'
            scope:
              - profile
              - email